# Set the equipment that will be issued to players
# Items are followed by a name that will be set for each item.
equipment:
  hunter:
    items:
      - 268 Stake
  vampire:
    items:
      - 267 Vampire Blade
# Set the number of ticks a player will burn if they are out in the sun
# as a vampire - the schedule checks for burn every 200 ticks (10 Seconds)
vburn: 100
