name: vHunter
main: com.digitalbrainery.vHunter.vHunter
version: 0.1.1-BETA
website: meloncraft.likes-pie.com
description: vHunter Plugin for CraftBukkit
authors: [FilchersSoup]

commands:
  vhunter:
    description: Base command for vHunter
    usage: /vHunter <command>
    aliases: [vh,vhunt]
    

permissions:
  vhunter.*:
    description: Give players with op everything by default
    default: op
    children:
      vhunter.basic: true
      vhunter.clrflag: true
      vhunter.signpost: true
      vhunter.vwarp: true
  vhunter.basic:
    description: The most basic command
    default: op
  vhunter.clrflag:
    description: Remove vHunter flag from a player.
    default: op
  vhunter.signpost:
    description: Create Enter and Exit signs for vHunter.
    default: op
  vhunter.vwarp:
    description: Warp to and from the vampire world.
    default: op